INSERT INTO CVARS(engine, show_inverted, varname, vartype, vardefault) VALUES
(0, false, 'skill', 'Int', '2'),
(0, false, 'botskill', 'Int', '2'),
/*
(0, false, 'dmflags', 'Int', '0'),
(0, false, 'dmflags2', 'Int', '0'),
(0, false, 'zadmflags', 'Int', '0'),
(0, false, 'compatflags', 'Int', '0'),
(0, false, 'zacompatflags', 'Int', '0'),

(0, false, 'sv_cheats', 'Bool', 'false'),
*/
(0, false, 'sv_coopspawnvoodoodolls', 'Bool', 'true'),
(0, false, 'sv_coopunassignedvoodoodolls', 'Bool', 'true'),
(0, false, 'sv_coopunassignedvoodoodollsfornplayers', 'Int', '64'),
(0, false, 'cooperative', 'Bool', 'true'),
(0, false, 'survival', 'Bool', 'false'),
(0, false, 'invasion', 'Bool', 'false'),
(0, false, 'sv_unlimited_pickup', 'Bool', 'false'),
(0, false, 'deathmatch', 'Bool', 'false'),
(0, false, 'teamplay', 'Bool', 'false'),
(0, false, 'duel', 'Bool', 'false'),
(0, false, 'terminator', 'Bool', 'false'),
(0, false, 'lastmanstanding', 'Bool', 'false'),
(0, false, 'teamlms', 'Bool', 'false'),
(0, false, 'possession', 'Bool', 'false'),
(0, false, 'teampossession', 'Bool', 'false'),
(0, false, 'fraglimit', 'Int', '0'),
(0, false, 'timelimit', 'Float', '0.0'),
(0, false, 'lobby', 'String', ''),
(0, false, 'var_friction', 'Bool', 'true'),
(0, false, 'var_pushers', 'Bool', 'true'),
(0, false, 'alwaysapplydmflags', 'Bool', 'false'),
(0, false, 'teamdamage', 'Float', '0'),
(0, false, 'infighting', 'Int', '0'),
(0, false, 'instagib', 'Bool', 'false'),
(0, false, 'buckshot', 'Bool', 'false'),
(0, false, 'sv_suddendeath', 'Bool', 'true'),
(0, false, 'maxviewpitch', 'Float', '90'),
(0, false, 'sv_useteamstartsindm', 'Bool', 'false'),
(0, false, 'sv_randomcoopstarts', 'Bool', 'false'),
(0, false, 'sv_corpsequeuesize', 'Int', '64'),
(0, false, 'sv_artifactreturntime', 'Int', '30'),
(0, false, 'wavelimit', 'Int', '0'),
(0, false, 'winlimit', 'Int', '0'),
(0, false, 'lmsallowedweapons', 'Int', '1023'),
(0, false, 'lmsspectatorsettings', 'Int', '2'),
(0, false, 'sv_dropstyle', 'Int', '0'),
(0, false, 'sv_disableautohealth', 'Bool', 'false'),
(0, false, 'sv_coop_damagefactor', 'Float', '1'),
(0, false, 'sv_smartaim', 'Int', '0'),
(0, false, 'splashfactor', 'Float', '1'),
(0, false, 'sv_gravity', 'Float', '800'),
(0, false, 'sv_fastweapons', 'Int', '0'),
(0, false, 'genblockmap', 'Bool', 'false'),
(0, false, 'gennodes', 'Bool', 'false'),
(0, false, 'genglnodes', 'Bool', 'false'),
(0, false, 'sv_killallmonsters_percentage', 'Int', '100'),
(0, false, 'forcewater', 'Bool', 'false'),
(0, false, 'sv_aircontrol', 'Float', '0.00390625'),
(0, false, 'sv_maxlives', 'Int', '0'),
(0, false, 'sv_pure', 'Bool', 'true'),
(0, false, 'sv_updatemaster', 'Bool', 'true'),
(0, false, 'teamgame', 'Bool', 'false'),
(0, false, 'ctf', 'Bool', 'false'),
(0, false, 'oneflagctf', 'Bool', 'false'),
(0, false, 'skulltag', 'Bool', 'false'),
(0, false, 'domination', 'Bool', 'false'),
(0, false, 'pointlimit', 'Int', '0'),
(0, false, 'sv_maxteams', 'Int', '2'),

-- dmflags),
(0, true , 'sv_nohealth', 'Bool', 'false'),
(0, true , 'sv_noitems', 'Bool', 'false'),
(0, false, 'sv_weaponstay', 'Bool', 'false'),
(0, false, 'sv_falldamage', 'Bool', 'false'),
(0, false, 'sv_oldfalldamage', 'Bool', 'false'),
(0, false, 'sv_samelevel', 'Bool', 'false'),
(0, false, 'sv_spawnfarthest', 'Bool', 'false'),
(0, false, 'sv_forcerespawn', 'Bool', 'false'),
(0, true , 'sv_noarmor', 'Bool', 'false'),
(0, true , 'sv_noexit', 'Bool', 'false'),
(0, false, 'sv_infiniteammo', 'Bool', 'false'),
(0, true , 'sv_nomonsters', 'Bool', 'false'),
(0, false, 'sv_monsterrespawn', 'Bool', 'false'),
(0, false, 'sv_itemrespawn', 'Bool', 'false'),
(0, false, 'sv_fastmonsters', 'Bool', 'false'),
(0, true , 'sv_nojump', 'Bool', 'false'),
(0, false, 'sv_allowjump', 'Bool', 'false'),
(0, true , 'sv_nofreelook', 'Bool', 'false'),
(0, false, 'sv_respawnsuper', 'Bool', 'false'),
(0, true , 'sv_nofov', 'Bool', 'false'),
(0, true , 'sv_noweaponspawn', 'Bool', 'false'),
(0, true , 'sv_nocrouch', 'Bool', 'false'),
(0, false, 'sv_allowcrouch', 'Bool', 'false'),
(0, false, 'sv_coop_loseinventory', 'Bool', 'false'),
(0, false, 'sv_coop_losekeys', 'Bool', 'false'),
(0, false, 'sv_coop_loseweapons', 'Bool', 'false'),
(0, false, 'sv_coop_losearmor', 'Bool', 'false'),
(0, false, 'sv_coop_losepowerups', 'Bool', 'false'),
(0, false, 'sv_coop_loseammo', 'Bool', 'false'),
(0, false, 'sv_coop_halveammo', 'Bool', 'false'),

-- dmflags2
(0, false, 'sv_weapondrop', 'Bool', 'false'),
(0, true , 'sv_noteamswitch', 'Bool', 'false'),
(0, false, 'sv_doubleammo', 'Bool', 'false'),
(0, false, 'sv_degeneration', 'Bool', 'false'),
(0, false, 'sv_bfgfreeaim', 'Bool', 'false'),
(0, false, 'sv_barrelrespawn', 'Bool', 'false'),
(0, false, 'sv_keepfrags', 'Bool', 'false'),
(0, true , 'sv_norespawn', 'Bool', 'false'),
(0, false, 'sv_losefrag', 'Bool', 'false'),
(0, true , 'sv_norespawninvul', 'Bool', 'false'),
(0, false, 'sv_samespawnspot', 'Bool', 'false'),
(0, false, 'sv_infiniteinventory', 'Bool', 'false'),
(0, false, 'sv_killallmonsters', 'Bool', 'false'),
(0, true , 'sv_noautomap', 'Bool', 'false'),
(0, true , 'sv_noautomapallies', 'Bool', 'false'),
(0, false, 'sv_disallowspying', 'Bool', 'false'),
(0, false, 'sv_chasecam', 'Bool', 'false'),
(0, false, 'sv_disallowsuicide', 'Bool', 'false'),
(0, true , 'sv_noautoaim', 'Bool', 'false'),
(0, false, 'sv_dontcheckammo', 'Bool', 'false'),
(0, false, 'sv_killbossmonst', 'Bool', 'false'),
(0, true , 'sv_norunes', 'Bool', 'false'),
(0, false, 'sv_instantreturn', 'Bool', 'false'),
(0, true , 'sv_noteamselect', 'Bool', 'false'),
(0, false, 'sv_shotgunstart', 'Bool', 'false'),

-- zadmflags
(0, true , 'sv_noidentifytarget', 'Bool', 'false'),
(0, false, 'sv_applylmsspectatorsettings', 'Bool', 'false'),
(0, true , 'sv_nocoopinfo', 'Bool', 'false'),
(0, false, 'sv_unblockplayers', 'Bool', 'false'),
(0, true , 'sv_nomedals', 'Bool', 'false'),
(0, false, 'sv_sharekeys', 'Bool', 'false'),
(0, false, 'sv_keepteams', 'Bool', 'false'),
(0, false, 'sv_forcegldefaults', 'Bool', 'false'),
(0, true , 'sv_norocketjumping', 'Bool', 'false'),
(0, false, 'sv_awarddamageinsteadkills', 'Bool', 'false'),
(0, false, 'sv_forcealpha', 'Bool', 'false'),
(0, false, 'sv_coop_spactorspawn', 'Bool', 'false'),
(0, false, 'sv_maxbloodscalar', 'Bool', 'false'),
(0, false, 'sv_unblockallies', 'Bool', 'false'),

-- compatflags
(0, false, 'compat_shortTex', 'Bool', 'false'),
(0, false, 'compat_stairs', 'Bool', 'false'),
(0, false, 'compat_limitpain', 'Bool', 'false'),
(0, false, 'compat_silentpickup', 'Bool', 'false'),
(0, false, 'compat_nopassover', 'Bool', 'false'),
(0, false, 'compat_soundslots', 'Bool', 'false'),
(0, false, 'compat_wallrun', 'Bool', 'false'),
(0, false, 'compat_notossdrops', 'Bool', 'false'),
(0, false, 'compat_useblocking', 'Bool', 'false'),
(0, false, 'compat_nodoorlight', 'Bool', 'false'),
(0, false, 'compat_ravenscroll', 'Bool', 'false'),
(0, false, 'compat_soundtarget', 'Bool', 'false'),
(0, false, 'compat_dehhealth', 'Bool', 'false'),
(0, false, 'compat_trace', 'Bool', 'false'),
(0, false, 'compat_dropoff', 'Bool', 'false'),
(0, false, 'compat_boomscroll', 'Bool', 'false'),
(0, false, 'compat_invisibility', 'Bool', 'false'),
(0, false, 'compat_silentinstantfloors', 'Bool', 'false'),
(0, false, 'compat_sectorsounds', 'Bool', 'false'),
(0, false, 'compat_missileclip', 'Bool', 'false'),
(0, false, 'compat_crossdropoff', 'Bool', 'false'),
(0, false, 'compat_anybossdeath', 'Bool', 'false'),
(0, false, 'compat_minotaur', 'Bool', 'false'),
(0, false, 'compat_mushroom', 'Bool', 'false'),
(0, false, 'compat_mbfmonstermove', 'Bool', 'false'),
(0, false, 'compat_corpsegibs', 'Bool', 'false'),
(0, false, 'compat_noblockfriends', 'Bool', 'false'),
(0, false, 'compat_spritesort', 'Bool', 'false'),
(0, false, 'compat_hitscan', 'Bool', 'false'),
(0, false, 'compat_light', 'Bool', 'false'),
(0, false, 'compat_polyobj', 'Bool', 'false'),

-- zacompatflags
(0, false, 'compat_limited_airmovement', 'Bool', 'false'),
(0, false, 'compat_plasmabump', 'Bool', 'false'),
(0, false, 'compat_instantrespawn', 'Bool', 'false'),
(0, false, 'compat_disabletaunts', 'Bool', 'false'),
(0, false, 'compat_originalsoundcurve', 'Bool', 'false'),
(0, false, 'compat_oldintermission', 'Bool', 'false'),
(0, false, 'compat_disablestealthmonsters', 'Bool', 'false'),
(0, false, 'compat_oldradiusdmg', 'Bool', 'false'),
(0, false, 'compat_nocrosshair', 'Bool', 'false'),
(0, false, 'compat_oldweaponswitch', 'Bool', 'false'),
(0, false, 'compat_netscriptsareclientside', 'Bool', 'false'),
(0, false, 'compat_clientssendfullbuttoninfo', 'Bool', 'false'),
(0, false, 'compat_noland', 'Bool', 'false'),
(0, false, 'compat_oldrandom', 'Bool', 'false'),
(0, false, 'compat_nogravity_spheres', 'Bool', 'false'),
(0, false, 'compat_dont_stop_player_scripts_on_disconnect', 'Bool', 'false'),
(0, false, 'compat_explosionthrust', 'Bool', 'false'),
(0, false, 'compat_bridgedrops', 'Bool', 'false'),
(0, false, 'compat_oldzdoomzmovement', 'Bool', 'false'),
(0, false, 'compat_fullweaponlower', 'Bool', 'false'),
(0, false, 'compat_autoaim', 'Bool', 'false'),
(0, false, 'compat_silentwestspawns', 'Bool', 'false')
;